---
name: kong

instance_groups:
- name: kong
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: kong
    release: kong-ce
    properties: 
      kong_conf: |
        database = postgres
        pg_host = 127.0.0.1
        pg_port = 5432
        pg_user = kong
        pg_password = kong
        pg_database = kong

  - name: smoke-tests
    release: kong-ce

  - name: postgres
    release: postgres
    properties:
      databases: 
        databases:
        - name: kong
          citext: true
        port: 5432
        roles:
        - name: kong
          password: kong
          permissions:
          - "SUPERUSER"

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: kong-ce
  version: "1.0.0"
  url: https://github.com/gstackio/kong-ce-boshrelease/releases/download/v1.0.0/kong-ce-1.0.0.tgz
  sha1: f829807866f70361b7593747bf079eeb8dd6f775
- name: postgres
  version: "30"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=30
  sha1: a798999d29b9f5aa12035cff907b26674b491200
