---
name: kong

instance_groups:
- name: kong
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: kong
    release: kong
    properties: 
      kong_conf: |
        database = postgres
        pg_host = 127.0.0.1
        pg_port = 5432
        pg_user = kong
        pg_password = kong
        pg_database = kong

  - name: postgres
    release: postgres
    properties:
      databases: 
        databases:
        - name: kong
          citext: true
        port: 5432
        roles:
        - name: kong
          password: kong
          permissions:
          - "SUPERUSER"

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: kong
  version: latest
- name: postgres
  version: 21
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=21
  sha1: b37916b709fb45ac7de3e195456301cb01a1ae22